version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    depends_on:
      - server
    env_file:
      - frontend/.env
  server:
    build:
      context: ./server
    ports:
      - 8080:8080
    volumes:
      - ./server:/app
    env_file:
      - server/.env
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: 'boards'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
